/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BOOLEANVALUE = 1;
  /** RegularExpression Id. */
  int TYPENAMESTRING = 2;
  /** RegularExpression Id. */
  int MAIN = 3;
  /** RegularExpression Id. */
  int LENGTH = 4;
  /** RegularExpression Id. */
  int SYSTEMOUTPRINTLN = 5;
  /** RegularExpression Id. */
  int ABSTRACT = 6;
  /** RegularExpression Id. */
  int ASSERT = 7;
  /** RegularExpression Id. */
  int BOOLEAN = 8;
  /** RegularExpression Id. */
  int BREAK = 9;
  /** RegularExpression Id. */
  int BYTE = 10;
  /** RegularExpression Id. */
  int CASE = 11;
  /** RegularExpression Id. */
  int CATCH = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int CLASS = 14;
  /** RegularExpression Id. */
  int CONST = 15;
  /** RegularExpression Id. */
  int CONTINUE = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int DOUBLE = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int ENUM = 20;
  /** RegularExpression Id. */
  int EXTENDS = 21;
  /** RegularExpression Id. */
  int FINAL = 22;
  /** RegularExpression Id. */
  int FINALLY = 23;
  /** RegularExpression Id. */
  int FLOAT = 24;
  /** RegularExpression Id. */
  int FOR = 25;
  /** RegularExpression Id. */
  int GOTO = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int IMPLEMENTS = 28;
  /** RegularExpression Id. */
  int IMPORT = 29;
  /** RegularExpression Id. */
  int INSTANCEOF = 30;
  /** RegularExpression Id. */
  int INT = 31;
  /** RegularExpression Id. */
  int INTERFACE = 32;
  /** RegularExpression Id. */
  int LONG = 33;
  /** RegularExpression Id. */
  int NATIVE = 34;
  /** RegularExpression Id. */
  int NEW = 35;
  /** RegularExpression Id. */
  int PACKAGE = 36;
  /** RegularExpression Id. */
  int PRIVATE = 37;
  /** RegularExpression Id. */
  int PROTECTED = 38;
  /** RegularExpression Id. */
  int PUBLIC = 39;
  /** RegularExpression Id. */
  int RETURN = 40;
  /** RegularExpression Id. */
  int SHORT = 41;
  /** RegularExpression Id. */
  int STATIC = 42;
  /** RegularExpression Id. */
  int STRICTFP = 43;
  /** RegularExpression Id. */
  int SUPER = 44;
  /** RegularExpression Id. */
  int SWITCH = 45;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 46;
  /** RegularExpression Id. */
  int THIS = 47;
  /** RegularExpression Id. */
  int THROW = 48;
  /** RegularExpression Id. */
  int THROWS = 49;
  /** RegularExpression Id. */
  int TRANSIENT = 50;
  /** RegularExpression Id. */
  int TRY = 51;
  /** RegularExpression Id. */
  int UNDERSCORE = 52;
  /** RegularExpression Id. */
  int VOID = 53;
  /** RegularExpression Id. */
  int VOLATILE = 54;
  /** RegularExpression Id. */
  int WHILE = 55;
  /** RegularExpression Id. */
  int IDENTIFIER = 56;
  /** RegularExpression Id. */
  int LETTER = 57;
  /** RegularExpression Id. */
  int DIGIT = 58;
  /** RegularExpression Id. */
  int DECIMAL_NUMERAL = 59;
  /** RegularExpression Id. */
  int ZERO = 60;
  /** RegularExpression Id. */
  int NON_ZERO_DIGIT = 61;
  /** RegularExpression Id. */
  int DIGITS = 62;
  /** RegularExpression Id. */
  int DIGITS_AND_UNDERSCORES = 63;
  /** RegularExpression Id. */
  int UNDERSCORES = 64;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT = 65;
  /** RegularExpression Id. */
  int EXPONENT_PART = 66;
  /** RegularExpression Id. */
  int EXPONENT_INDICATOR = 67;
  /** RegularExpression Id. */
  int SIGNED_INTEGER = 68;
  /** RegularExpression Id. */
  int SIGN = 69;
  /** RegularExpression Id. */
  int FLOAT_TYPE_SUFFIX = 70;
  /** RegularExpression Id. */
  int STRING_LITERAL = 71;
  /** RegularExpression Id. */
  int STRING_CHARACTER = 72;
  /** RegularExpression Id. */
  int SEPARATORS = 73;
  /** RegularExpression Id. */
  int OPERATORS = 74;
  /** RegularExpression Id. */
  int SPACES = 75;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<BOOLEANVALUE>",
    "\"String\"",
    "\"main\"",
    "\"length\"",
    "\"System.out.println\"",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"try\"",
    "\"_\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL_NUMERAL>",
    "\"0\"",
    "<NON_ZERO_DIGIT>",
    "<DIGITS>",
    "<DIGITS_AND_UNDERSCORES>",
    "<UNDERSCORES>",
    "<DECIMAL_FLOATING_POINT>",
    "<EXPONENT_PART>",
    "<EXPONENT_INDICATOR>",
    "<SIGNED_INTEGER>",
    "<SIGN>",
    "<FLOAT_TYPE_SUFFIX>",
    "<STRING_LITERAL>",
    "<STRING_CHARACTER>",
    "<SEPARATORS>",
    "<OPERATORS>",
    "<SPACES>",
  };

}
