public enum TokenType {
    CLASS, PUBLIC, STATIC, VOID, MAIN, A_PALAVRA_STRING, EXTENDS, 
    ID, NUM_DECIM, BOOLEAN_TYPE,
    ABRE_CHAVE, FECHA_CHAVE,
    ABRE_COLCHETE, FECHA_COLCHETE,
    ABRE_PARENTESE, FECHA_PARENTESE,
    PONTO, VIRGULA, PONTO_E_VIRGULA, IGUAL,
    OP_E, OP_OU, OP_MENOR, OP_MAIS, OP_MENOS, OP_VEZES, OP_EXCLAMACAO,
    INT, BOOLEAN_VALUE,
    NEW, THIS,
    SYSTEM_OUT_PRINTLN,
    WHILE, IF, ELSE, RETURN, TYPE_NAME_STRING, LENGTH, ACC,
    I, Cx, M, C, Vx, V, Fx, F, Px, Pz, T, Sx, S, E, Ex, Ez ;
}

